---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dkr-nginx-deployment
  namespace: test-ns
  labels:
    app: dkr-nginx-deployment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dkr-nginx-deployment-app
  template:
    metadata:
      labels:
        app: dkr-nginx-deployment-app
    spec:
      containers:
      - name: dkr-nginx-container
        image: quay.io/anil_apato/cape-quay-reg:nginx
        imagePullPolicy: Always
      imagePullSecrets:
        - name: sample-dkr-registry